### ISSUE TITLE
USE_FAMISTUDIO_MUSIC breaks compilation

### ISSUE THREAD

**Issue by craftersshaft** [smbstudio/smb1base#2]
compliation seems to work fine with the default settings, but enabling this without changing any other file causes this error:

`ld65: Warning: smb1base.cfg:2: Segment 'ZEROPAGE' overflows memory area 'ZP' by 3 bytes
ld65: Error: Cannot generate most of the files due to memory area overflow`

it seems to compile fine if USE_CUSTOM_TITLESCREEN and ENABLE_C_CODE are disabled, so maybe it's just a case of having too many things being added at once

**Comment by jroweboy** [comment]
Thanks for the report! I'll get this fixed today.

**Comment by jroweboy** [comment]
Fixed in 7ea34af994a3c80904fe217ee76ac9c93207b996

Let us know if you have any further problems or questions!

**Comment by craftersshaft** [comment]
This seems to work mostly fine now, and thank you so much!! the bonus room pipes seem to be broken but i'm not sure if that's a related issue

https://github.com/user-attachments/assets/194942c3-ee25-410b-b02d-1c2396ef6928

https://github.com/user-attachments/assets/6bd0213c-1f33-45c5-81b8-b597eadca70d

**Comment by jroweboy** [comment]
Ack! I caused this just now. Good catch, i'll fix it asap

**Comment by jroweboy** [comment]
Okay, fixed for real in b7e9ce0
